# Generated by Django 5.2.6 on 2025-11-12 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aplicaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
                ('estatus', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Problemas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
                ('estatus', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('orden', models.IntegerField(primary_key=True, serialize=False)),
                ('oficio', models.CharField(default='S/N', max_length=20)),
                ('usuario_solicita', models.IntegerField()),
                ('usuario_asigna', models.IntegerField()),
                ('telefono', models.CharField(max_length=15)),
                ('clasificacion', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('solucion', models.TextField()),
                ('prioridad', models.CharField(max_length=20)),
                ('equipo', models.CharField(max_length=50)),
                ('captura', models.IntegerField()),
                ('fecha_captura', models.DateTimeField(auto_now=True)),
                ('estatus', models.CharField(max_length=20)),
                ('capacitacion', models.CharField(max_length=100)),
                ('capacitacion_descripcion', models.TextField()),
                ('fecha_terminado', models.DateTimeField(blank=True, null=True)),
                ('aplicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordenes.aplicaciones')),
                ('problema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordenes.problemas')),
            ],
        ),
    ]
