# Generated by Django 5.2.6 on 2025-11-12 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0002_clasificaciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='clasificacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordenes.clasificaciones'),
        ),
    ]
