# Generated by Django 5.2.6 on 2025-11-13 21:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0003_alter_orden_clasificacion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Colores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=100)),
                ('estatus', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Marcas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=100)),
                ('estatus', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='orden',
            name='equipo',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='EquipoXOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipo', models.CharField(max_length=100)),
                ('patrimonio', models.CharField(max_length=50)),
                ('serie', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('entregado_foraneo', models.IntegerField(choices=[(0, 'Dentro'), (1, 'Foraneo')])),
                ('observaciones', models.TextField()),
                ('salida', models.IntegerField()),
                ('nombre_resguardante', models.CharField(max_length=100)),
                ('area_resguardante', models.CharField(max_length=100)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordenes.colores')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipos', to='ordenes.orden')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordenes.marcas')),
            ],
        ),
        migrations.CreateModel(
            name='UsuariosxOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicia', models.DateTimeField(blank=True, null=True)),
                ('termina', models.DateTimeField(blank=True, null=True)),
                ('fecha_asigna', models.DateTimeField(auto_now=True)),
                ('estatus_orden', models.CharField(max_length=2)),
                ('estatus', models.CharField(max_length=2)),
                ('causa', models.CharField(max_length=100)),
                ('etiquetas', models.CharField(max_length=100)),
                ('asigna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asigna_usuario', to=settings.AUTH_USER_MODEL)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordenes.orden')),
                ('realiza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
