# Generated by Django 5.2.6 on 2025-11-14 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0004_colores_marcas_alter_orden_equipo_equipoxorden_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colores',
            name='estatus',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='marcas',
            name='estatus',
            field=models.CharField(max_length=2),
        ),
    ]
