# Generated by Django 4.2.26 on 2025-11-14 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0005_alter_colores_estatus_alter_marcas_estatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='oficio',
            field=models.CharField(blank=True, default='S/N', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='orden',
            name='orden',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
