# Generated by Django 4.2.26 on 2025-11-14 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0006_alter_orden_oficio_alter_orden_orden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipoxorden',
            name='area_resguardante',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='equipoxorden',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='equipoxorden',
            name='equipo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='equipoxorden',
            name='nombre_resguardante',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='equipoxorden',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
    ]
