# Generated by Django 4.2.26 on 2025-11-14 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0007_alter_equipoxorden_area_resguardante_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipoxorden',
            name='salida',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
