# Generated by Django 4.2.26 on 2025-11-14 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0008_alter_equipoxorden_salida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='capacitacion_descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orden',
            name='estatus',
            field=models.CharField(default='A', max_length=2),
        ),
        migrations.AlterField(
            model_name='orden',
            name='solucion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orden',
            name='telefono',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
