# Generated by Django 4.2.26 on 2025-11-14 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0009_alter_orden_capacitacion_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='capacitacion',
            field=models.CharField(default='N', max_length=100),
        ),
        migrations.AlterField(
            model_name='orden',
            name='captura',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
