# Generated by Django 4.2.26 on 2025-11-19 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0010_alter_orden_capacitacion_alter_orden_captura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='capacitacion',
            field=models.CharField(blank=True, default='N', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='orden',
            name='estatus',
            field=models.CharField(blank=True, default='A', max_length=2, null=True),
        ),
        migrations.CreateModel(
            name='SolicitantexOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solicitante', models.IntegerField()),
                ('nombre_solicitante', models.CharField(blank=True, max_length=100, null=True)),
                ('puesto_solicitante', models.CharField(blank=True, max_length=100, null=True)),
                ('dependencia_solicitante', models.CharField(blank=True, max_length=100, null=True)),
                ('correo_solicitante', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono_solicitante', models.CharField(blank=True, max_length=15, null=True)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordenes.orden')),
            ],
        ),
    ]
