# Generated by Django 4.2.26 on 2025-11-19 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0011_alter_orden_capacitacion_alter_orden_estatus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitantexorden',
            name='beneficiado',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solicitantexorden',
            name='correo_beneficiado',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='solicitantexorden',
            name='dependencia_beneficiado',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='solicitantexorden',
            name='nombre_beneficiado',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='solicitantexorden',
            name='puesto_beneficiado',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='solicitantexorden',
            name='telefono_beneficiado',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
