# Generated by Django 4.2.26 on 2025-11-19 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0012_solicitantexorden_beneficiado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitantexorden',
            name='orden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitantes', to='ordenes.orden'),
        ),
    ]
