# Generated by Django 4.2.26 on 2025-11-20 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0013_alter_solicitantexorden_orden'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orden',
            old_name='usuario_asigna',
            new_name='usuario_beneficiado',
        ),
    ]
