# Generated by Django 4.2.26 on 2025-11-20 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0014_rename_usuario_asigna_orden_usuario_beneficiado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariosxorden',
            name='causa',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='usuariosxorden',
            name='estatus',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='usuariosxorden',
            name='estatus_orden',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='usuariosxorden',
            name='etiquetas',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
