# Generated by Django 4.2.26 on 2025-11-20 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0015_alter_usuariosxorden_causa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariosxorden',
            name='orden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios_orden', to='ordenes.orden'),
        ),
    ]
