# Generated by Django 4.2.26 on 2025-11-21 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0016_alter_usuariosxorden_orden'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solicitantexorden',
            old_name='beneficiado',
            new_name='usuario_beneficiado',
        ),
        migrations.RenameField(
            model_name='solicitantexorden',
            old_name='solicitante',
            new_name='usuario_solicita',
        ),
    ]
