# Generated by Django 4.2.26 on 2025-11-21 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0017_rename_beneficiado_solicitantexorden_usuario_beneficiado_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SolicitantexOrden',
        ),
    ]
