# Generated by Django 4.2.26 on 2025-11-21 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0018_delete_solicitantexorden'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitantexOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_beneficiado', models.IntegerField()),
                ('nombre_beneficiado', models.CharField(blank=True, max_length=100, null=True)),
                ('puesto_beneficiado', models.CharField(blank=True, max_length=100, null=True)),
                ('dependencia_beneficiado', models.CharField(blank=True, max_length=100, null=True)),
                ('correo_beneficiado', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono_beneficiado', models.CharField(blank=True, max_length=15, null=True)),
                ('usuario_solicita', models.IntegerField()),
                ('nombre_solicitante', models.CharField(blank=True, max_length=100, null=True)),
                ('puesto_solicitante', models.CharField(blank=True, max_length=100, null=True)),
                ('dependencia_solicitante', models.CharField(blank=True, max_length=100, null=True)),
                ('correo_solicitante', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono_solicitante', models.CharField(blank=True, max_length=15, null=True)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitantes', to='ordenes.orden')),
            ],
        ),
    ]
