# Generated by Django 4.2.26 on 2025-11-25 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0019_solicitantexorden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='estatus',
            field=models.CharField(blank=True, choices=[('A', 'Asignada'), ('E', 'En proceso'), ('C', 'Cancelada'), ('T', 'Terminada')], default='A', max_length=2, null=True),
        ),
    ]
