# Generated by Django 4.2.26 on 2025-11-27 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0020_alter_orden_estatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitantexorden',
            name='puesto_beneficiado',
            field=models.CharField(default='Presidente', max_length=100),
            preserve_default=False,
        ),
    ]
