# Generated by Django 4.2.26 on 2025-11-27 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0021_alter_solicitantexorden_puesto_beneficiado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariosxorden',
            name='fecha_asigna',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
