# Generated by Django 4.2.26 on 2025-11-27 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0022_alter_usuariosxorden_fecha_asigna'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='fecha_captura',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
