# Generated by Django 4.2.26 on 2025-11-27 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0023_alter_orden_fecha_captura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='oficio',
            field=models.CharField(blank=True, default='S/N', max_length=25, null=True),
        ),
    ]
