# Generated by Django 4.2.26 on 2025-11-27 21:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ordenes', '0024_alter_orden_oficio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariosxorden',
            name='asigna',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asigna_usuario', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usuariosxorden',
            name='realiza',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
