# Generated by Django 4.2.26 on 2025-12-02 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0025_alter_usuariosxorden_asigna_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='fecha_inicio',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
