# Generated by Django 4.2.26 on 2025-12-02 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0026_orden_fecha_inicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariosxorden',
            name='comentarios',
            field=models.TextField(blank=True, null=True),
        ),
    ]
