# Generated by Django 4.2.26 on 2025-12-03 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0027_usuariosxorden_comentarios'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orden',
            name='problema',
        ),
        migrations.AlterField(
            model_name='usuariosxorden',
            name='estatus',
            field=models.CharField(blank=True, choices=[('A', 'Asignada'), ('E', 'En proceso'), ('C', 'Cancelada'), ('T', 'Terminada')], null=True),
        ),
        migrations.DeleteModel(
            name='Problemas',
        ),
    ]
