# Generated by Django 4.2.26 on 2025-12-08 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0028_remove_orden_problema_alter_usuariosxorden_estatus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='prioridad',
            field=models.CharField(choices=[('minima', 'Mínima'), ('inmediata', 'Inmediata'), ('urgente', 'Urgente'), ('programada', 'Programada'), ('normal', 'Normal')], max_length=12),
        ),
    ]
