# Generated by Django 4.2.26 on 2025-12-18 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0029_alter_orden_prioridad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='fecha_captura',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='usuariosxorden',
            name='estatus_orden',
            field=models.CharField(blank=True, choices=[('A', 'Asignada'), ('E', 'En proceso'), ('C', 'Cancelada'), ('T', 'Terminada')], null=True),
        ),
    ]
