# Generated by Django 4.2.26 on 2025-12-29 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0030_alter_orden_fecha_captura_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenxArchivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='archivos_ordenes/')),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='ordenes.orden')),
            ],
        ),
    ]
