# Generated by Django 4.2.26 on 2026-01-08 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0031_ordenxarchivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitantexorden',
            name='telefono_beneficiado',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='solicitantexorden',
            name='telefono_solicitante',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
