# Generated by Django 4.2.26 on 2026-01-13 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0033_usuariosxorden_solucion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='estatus',
            field=models.CharField(blank=True, choices=[('A', 'Asignada'), ('E', 'En proceso'), ('C', 'Cancelada'), ('T', 'Terminada'), ('P', 'Aprobada')], default='A', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='usuariosxorden',
            name='estatus',
            field=models.CharField(blank=True, choices=[('A', 'Asignada'), ('E', 'En proceso'), ('C', 'Cancelada'), ('T', 'Terminada'), ('P', 'Aprobada')], null=True),
        ),
        migrations.AlterField(
            model_name='usuariosxorden',
            name='estatus_orden',
            field=models.CharField(blank=True, choices=[('A', 'Asignada'), ('E', 'En proceso'), ('C', 'Cancelada'), ('T', 'Terminada'), ('P', 'Aprobada')], null=True),
        ),
    ]
