# Generated by Django 4.2.26 on 2026-01-21 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0034_alter_orden_estatus_alter_usuariosxorden_estatus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordenxarchivo',
            name='descripcion',
            field=models.CharField(blank=True, null=True),
        ),
    ]
