# Generated by Django 4.2.26 on 2026-03-03 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0035_alter_ordenxarchivo_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='categoria',
            field=models.CharField(blank=True, choices=[('soporte_técnico', 'Soporte Técnico'), ('redes', 'Redes y Comunicaciones'), ('servidores', 'Servidores e Infraestructura'), ('programadores', 'Programadores y Desarrollo')], max_length=20, null=True),
        ),
    ]
