# Generated by Django 4.2.26 on 2026-03-03 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0036_orden_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='aviso_vencimiento',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orden',
            name='fecha_vencimiento',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
