# Generated by Django 4.2.26 on 2026-03-19 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0037_orden_aviso_vencimiento_orden_fecha_vencimiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orden',
            name='aviso_vencimiento',
        ),
        migrations.AddField(
            model_name='orden',
            name='nivel_alerta',
            field=models.IntegerField(default=0),
        ),
    ]
