# Generated by Django 4.2.26 on 2026-03-19 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0038_remove_orden_aviso_vencimiento_orden_nivel_alerta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='nivel_alerta',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
