# Generated by Django 4.2.26 on 2026-05-11 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0039_alter_orden_nivel_alerta'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='ultima_alerta_vencido',
            field=models.DateField(blank=True, null=True),
        ),
    ]
