# Generated by Django 4.2.26 on 2026-02-04 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0002_pushtoken'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PushToken',
        ),
    ]
