# Generated by Django 5.2.6 on 2025-11-12 21:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('estatus', models.CharField(max_length=2)),
                ('fecha_creacion', models.DateTimeField(auto_now=True)),
                ('fecha_baja', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExtraUsuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empleado', models.IntegerField()),
                ('estatus', models.CharField(max_length=2)),
                ('tipo', models.CharField(max_length=50)),
                ('notificaciones', models.IntegerField()),
                ('vacaciones', models.IntegerField()),
                ('reportar', models.IntegerField()),
                ('nivel_rep', models.IntegerField()),
                ('acronimo', models.CharField(max_length=10)),
                ('actualizado', models.IntegerField()),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.departamentos')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
