# Generated by Django 4.2.26 on 2025-11-19 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrausuarios',
            name='acronimo',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='extrausuarios',
            name='actualizado',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='extrausuarios',
            name='departamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.departamentos'),
        ),
        migrations.AlterField(
            model_name='extrausuarios',
            name='nivel_rep',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='extrausuarios',
            name='notificaciones',
            field=models.BooleanField(default=1),
        ),
        migrations.AlterField(
            model_name='extrausuarios',
            name='reportar',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='extrausuarios',
            name='vacaciones',
            field=models.BooleanField(default=0),
        ),
    ]
