# Generated by Django 4.2.26 on 2025-11-19 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_extrausuarios_acronimo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrausuarios',
            name='estatus',
            field=models.CharField(default='A', max_length=2),
        ),
    ]
