# Generated by Django 4.2.26 on 2025-11-19 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_extrausuarios_estatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrausuarios',
            name='empleado',
            field=models.IntegerField(unique=True),
        ),
    ]
