# Generated by Django 4.2.26 on 2025-11-25 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_alter_extrausuarios_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrausuarios',
            name='tipo',
            field=models.CharField(choices=[('P', 'Programador'), ('T', 'Técnico'), ('A', 'Administrador')], max_length=1),
        ),
    ]
