# Generated by Django 4.2.26 on 2025-11-25 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_alter_extrausuarios_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrausuarios',
            name='estatus',
            field=models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', max_length=2),
        ),
    ]
