# Generated by Django 4.2.26 on 2025-11-25 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_alter_extrausuarios_estatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrausuarios',
            name='tipo',
            field=models.CharField(choices=[('P', 'Programador'), ('T', 'Técnico'), ('R', 'Jefe de Progrmación'), ('E', 'Jefe de Técnicos'), ('A', 'Administrador')], max_length=1),
        ),
    ]
