# Generated by Django 4.2.26 on 2025-12-02 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0010_alter_extrausuarios_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrausuarios',
            name='estatus',
            field=models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo'), ('B', 'Baja')], default='A', max_length=2),
        ),
    ]
