# Generated by Django 4.2.26 on 2025-12-22 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0011_alter_extrausuarios_estatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='extrausuarios',
            name='cambio_contrasena',
            field=models.BooleanField(default=0),
        ),
    ]
