# Generated by Django 4.2.26 on 2026-05-15 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0012_extrausuarios_cambio_contrasena'),
    ]

    operations = [
        migrations.AddField(
            model_name='extrausuarios',
            name='permisos',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
