# Generated by Django 4.2.26 on 2025-12-05 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calificaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokencomentario',
            name='calificacion',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
