# Generated by Django 4.2.26 on 2025-12-05 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calificaciones', '0002_tokencomentario_calificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokencomentario',
            name='comentario',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tokencomentario',
            name='calificacion',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
