# Generated by Django 4.2.26 on 2025-12-08 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0029_alter_orden_prioridad'),
        ('calificaciones', '0003_tokencomentario_comentario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokencomentario',
            name='orden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentario', to='ordenes.orden'),
        ),
    ]
